---
title: "Conclusions"
bibliography: references.bib
---

```{r}
source(here::here("_chapter-setup.R"))
```

This forth edition of the Brazil-Europe operational ANS performance comparison report builds on the joint project between the Performance Section of DECEA and the Performance Review Unit of EUROCONTROL.
The collaboration aims at fostering the understanding and support the further development of approaches to measure operational performance in both regions.
This report builds on a subset of indicators and metrics established under the umbrella of ICAO’s Global Air Navigation Plan @icao_doc9750_2019.
The work is also used to showcase the application of the GANP indicators within a bi-regional and multi-regional project.
DECEA and EUROCONTROL engage actively within the international community and share their findings of their joint bi-regional work.

This iteration also comprised the integration of additional data source and topics.
A first characterisation of the different networks was introduced, and two additional topics studied.
The new data sources offer to perform more fine-grained analyses of the observed operational efficiency performance.
This will allow to further develop and complement the framework.
The report also identified several observations and ideas for future research which pave the way ahead for augmenting the associated set of comparison analyses.

This report kicked off by examining the commonalities and differences in terms of the organisation of air navigation services in both regions.
This was complemented by investigating the air traffic demand to better understand the factors influencing operational performance.
The air navigation service provision is less fragmented in Brazil than in Europe.
This plays out in the total number of air traffic service units.
Both regions operate a central flow management function to ensure network wide flow management.

In terms of air traffic demand, both regions were impacted by the unprecedented decline of air traffic.
Regional and global traffic restrictions resulted in different patterns.
With Europe zooming in on pre-pandemic traffic levels and Brazil consistently ranging above the pre-pandemic traffic, this report also marks the new reference for future iterations. 
Both regions - while having their separate challenges - have certainly completed the pandemic phase.
The traffic situation is also reflected by the demand at the study airports.
There is also a higher level of diversity in terms of air traffic evidenced by the share of light types serviced at the comparison airports.
International traffic is more centralised in Brazil than in Europe.

The observed punctuality in both regions was strongly influenced by the prevailing network effects.
Particularly, Europe suffered strongly from the impact of two years of record ATFM delays that further rippled down and amplified local constraint issues. This is evidenced by the high share of departure delays.
The reactionary knock-on effect amplified further the overall punctuality performance.

The utilisation of available runway system capacities is a fundamental enabler for high levels of operational performance.
This report showed that associated capacities are commensurate with the current traffic levels.
For the majority of airports, the realised throughput ranges still below the maximum declared capacities.

Operational efficiency is measured in this report in the form of the additional time during the surface movement phases and the terminal arrival phase.
On average, taxi-in operations are less constrained than taxi-out operations.
The observed performance varies across the airports and timeframe.
In terms of arrival management, air traffic in Brazil observed higher additional times in the terminal airspace.
This report showed that the scale effect of lower air traffic are potentially masked by the effects of airspace redesign in Brazil.
In the European region, it appears that the higher level of air traffic demand puts pressure on the arrival management and sequencing, and 2022 marks a return to higher additional times within the terminal airspace.
Further research can help to identify drivers and performance enablers.

The joint work also helped to promote the approach and state-of-the-art with the international community.
Both groups are contributing to the ICAO GANP Performance Expert Group and the multi-national Performance Benchmarking Working Group.
The wider harmonisation of performance related data and joint refinement of the guidance material and application of the performance framework start paying dividends.
For example, PBWG concluded in its most recent meeting to collaborate on topics of mutual interest for which this report supported the initial research and validation.

A further outcome of the project is the close technical collaboration.
It is planned to augment the report and its future editions with a rolling web-based monitoring, including regular updates of the underlying data.
This and future reports will help to complement the time series of the measures tracked.
