project:
  type: book
  #output-dir: docs    # use this output dir for anything updated on the public site
  output-dir: _book

# do not show output of code chunks - outside errors
execute:
  echo: false
  warning: false

book:
  title: "Operational Comparison of ANS Performance"
  author: "DECEA Performance Section, EUROCONTROL Performance Review Unit"
  date: today
  downloads: [pdf, docx]
  chapters:
  - index.qmd
  - 00-foreword.qmd
  - 00-executive-summary.qmd
  - 01-intro.qmd
  #- 02-system_overview.qmd
  - 03-traffic_characterisation.qmd
  # - 04-predictability.qmd
  # - 05-capacity_and_throughput.qmd
  # - 06-efficiency.qmd
 # - 07-environment.qmd
  # - 08-conclusions.qmd
  - 88-add-ons.qmd
  - 90-test-for-rafael.qmd
  - 99-references.qmd
  #appendices:
  #- A1-appendix.qmd

#bibliography: book.bib   #, packages.bib]
bibliography: references.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreport
  #   papersize: a4
  #   fig-pos: 'H'
  #   geometry:
  #   - top=30mm
  #   - right=30mm
  #   - left=30mm
  #   - bottom=30mm
  #   - heightrounded
  #   include-in-header:
  #     text: |
  #       \usepackage{pdfpages}
  #       \pagenumbering{gobble}
  #  
  docx:
    toc: true
    number-sections: true
    highlight-style: github
# epub:
#    cover-image: cover.png
